### ISSUE TITLE
Badge: Make small variant bigger

### ISSUE THREAD

**Issue by cseas** [hazel-ui/hazel-ui#31]
The small variant of the Badge component is too small to the point it's barely readable. Increase its size.

Suggestion:
Try these for reference:
Small: Storybook Tip example
Medium: GitHub labels
Large: Medium/GLUG topic tags

**Comment by samay-v** [comment]
I'd like to work on this issue.

Is the scope for this issue to change the size of all badges or just the `small` variant?

For the `small` variant we could start with `font-size: 1rem;` and increment 0.2rems on the consecutive variants.

Also, the padding on the badges look awkward since the top and bottom padding are not the same. I would like to create an issue for that and work on it as well, if not already being worked on.

**Comment by cseas** [comment]
Please go ahead. Feel free to modify the badge sizes as you see best fit.
The primary requirement is to change the small variant since it's so small it's actually hard to read.
But any improvements are welcome.

**Comment by samay-v** [comment]
Can close this I suppose 😅

**Comment by cseas** [comment]
Yes
